### PR TITLE
Task

### LINKED ISSUE #2: Observability on Task Service
1. Ganti bentuk logger dari console.log (dan sejenisnya) dengan winston, yang bentuknya info outputnya console saja, yang bentuknya error output nya console dan file, attachfile .log pada saat PR
2. implementasi jaeger untuk semua endpoint dengan ketentuan span sebagai berikut
- proses get data dari body (parsing)
- error (log, tag)
- process ke database
- process encoding dari hasil output database ke response
- hasil span process nya di screenshoot, cantumkan pada saat PR (on confirmed)

### PR DESCRIPTION
**Pull request by aliformer**

### CODE REVIEW

**Comment by aliformer** [comment]
image
image
image

**Comment by aliformer** [comment]
D:\bootcamp\day 22\22-service-observability\tugas\task-svc_error.log

**Comment by aliformer** [comment]
[task-svc_error.log](https://github.com/Kelompok-Gallium-Super-Bootcamp/22-service-observability/files/6002592/task-svc_error.log)

**Review by choirmalik — APPROVED** [review]
Oke

**Pull request merged**
